data_name: covertype
version: 3
num_data: 15000

# bandit
num_arm: 7
dim_context: 54
T: 15000

# train
algo: NeuralEpsGreedy
model: neural
act: ReLU
layers: [100]
num_iter: 100
eps: 0.4
lr: 0.1

# log
project: ContextualBandit-ICML
group: Covertype-NeuralEpsGreedy