data_name: covertype
version: 3
num_data: 15000

# bandit
num_arm: 7
dim_context: 54
T: 15000

# train
algo: NeuralTS
model: neural
act: ReLU
layers: [100]
loss: L2
num_iter: 100
lr: 0.01
reg: 0.001
nu: 0.01

# log
project: ContextualBandit-UCI
group: Covertype-NeuralTS