data_name: covertype
version: 3
num_data: 15000

# bandit
num_arm: 7
dim_context: 54
T: 15000

# train
algo: LMCTS
model: neural
act: LeakyReLU
layers: [100]
loss: BCE
num_iter: 100
beta_inv: 0.000001
lr: 0.01

# log
project: ContextualBandit-ICML
group: Covertype-LMCTS