data_name: MagicTelescope
version: 1
num_data: 19000

# bandit
num_arm: 2
dim_context: 10
T: 10000

# train
algo: NeuralTS
model: neural
act: ReLU
layers: [100]
num_iter: 100
lr: 0.01
reg: 0.00001
nu: 0.00001


# log
project: ContextualBandit-ICML
group: Magic-NeuralTS