data_name: mushroom
version: 1
num_data: 8000

# bandit
num_arm: 2
dim_context: 22
T: 10000

# train
algo: NeuralTS
model: neural
act: ReLU
layers: [100]
loss: L2
num_iter: 100
lr: 0.01
reg: 0.00001
nu: 0.00001

# log
project: ContextualBandit-ICML
group: Mushroom-NeuralTS