data_name: mushroom
version: 1
num_data: 8000

# bandit
num_arm: 2
dim_context: 22
T: 10000

# train
algo: LMCTS
model: neural
act: LeakyReLU
layers: [100]
reduce: 2
loss: L2
num_iter: 100
beta_inv: 0.000001
lr: 0.01

# log
project: ContextualBandit-ICML
group: Mushroom-LMCTS