data_name: shuttle
version: 1

# bandit
num_arm: 7
dim_context: 9
T: 10000

# train
algo: LMCTS
model: neural
act: LeakyReLU
layers: [50, 50, 50]
num_iter: 70
beta_inv: 0.0001
lr: 0.01

# log
project: ContextualBandit-ICML
group: Shuttle-LMCTS