data_name: mnist_784
version: 1
num_data: 50000

# bandit
num_arm: 10
dim_context: 784
T: 10000

# train
algo: LMCTS
model: neural
act: LeakyReLU
layers: [100, 50]
batchsize: 500
loss:
num_iter: 100
beta_inv: 0.00001
lr: 0.01

# log
project: ContextualBandit-ICML
group: MNIST-LMCTS