datapath: data/gaussian50-20-1-1.pt
# bandit
num_arm: 50
dim_context: 20

index: 0
num_data: 1
T: 10000
sigma: 0.0
func: logistic

# train
algo: GLMTSL
model: linear
loss: Logistic
num_iter: 100
tao: 30
nu: 0.01
reg: 0.0
lr: 0.01

# log
project: ContextualBandit-ICML
group: Logistic-GLMTSL