datapath: data/gaussian50-20-1-1.pt
# bandit
num_arm: 50
dim_context: 20
T: 10000
sigma: 0.0
func: logistic
index: 0
num_data: 1

# train
algo: EpsGreedy
model: linear
loss: Logistic
num_iter: 1
eps: 0.01

# log
project: ContextualBandit-ICML
group: Logistic-EpsGreedy