datapath: data/gaussian50-20-1-1.pt
# bandit
num_arm: 50
dim_context: 20
T: 10000
sigma: 1.0
func: quad

# train
algo: EpsGreedy
model: linear
num_iter: 1
eps: 0.9

# log
project: ContextualBandit-ICML
group: Quad-EpsGreedy